name: 'Stale handler'
on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  workflow_dispatch:
    inputs:
      debug-only:
        type: boolean
        description: "Does a dry-run when enabled. No PR's will be altered"
        required: true
        default: true

permissions:
  pull-requests: write
  actions: write
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Stale issues
        uses: actions/stale@v10
        id: stale-issues
        with:
          debug-only: ${{ github.event.inputs.debug-only == 'true' }}
          operations-per-run: 30
          days-before-stale: 60
          days-before-close: 30
          ignore-updates: false
          remove-stale-when-updated: true
          stale-issue-label: "stale"
          close-issue-label: "stale: closed"
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity during last 60 days :sleeping:

            It will be closed in 30 days if no further activity occurs. To unstale this issue, remove stale label or add a comment with a detailed explanation.

            There can be many reasons why some specific issue has no activity. The most probable cause is lack of time, not lack of interest.

            Thank you for your patience :heart:
          close-issue-message: |
            This issue has been automatically closed because it has been inactive during the last 30 days since being marked as stale.

            As author or maintainer, it can always be reopened if you see that carry on been useful.

            Anyway, thank you for your interest in contribute :heart:
          close-issue-reason: not_planned
          exempt-issue-labels: "blocked,must,should,keep,:busts_in_silhouette: discussion,:eyes: Needs Review,:pushpin: pinned"
          # disable PR processing at all (this step is for treat issues)
          days-before-pr-stale: -1
          days-before-pr-close: -1
          ignore-pr-updates: true
          remove-pr-stale-when-updated: false
          stale-pr-label: " "

      - name: Print outputs for issues
        run: echo ${{ format('{0},{1}', toJSON(steps.stale-issues.outputs.staled-issues-prs), toJSON(steps.stale-issues.outputs.closed-issues-prs)) }}

      - name: Stale Pull Requests
        uses: actions/stale@v10
        id: stale-prs
        with:
          debug-only: ${{ github.event.inputs.debug-only == 'true' }}
          operations-per-run: 30
          days-before-stale: 60
          days-before-close: 30
          ignore-updates: false
          remove-stale-when-updated: true
          stale-pr-label: "stale"
          close-pr-label: "stale: closed"
          stale-pr-message: |
            'This Pull Request has been automatically marked as stale because it has not had recent activity during last 60 days :sleeping:

            It will be closed in 30 days if no further activity occurs. To unstale this PR, draft it, remove stale label, comment with a detailed explanation or push more commits.

            There can be many reasons why some specific PR has no activity. The most probable cause is lack of time, not lack of interest.

            Thank you for your patience :heart:'
          close-pr-message: |
            This Pull Request has been automatically closed because it has been inactive during the last 30 days since being marked as stale.

            As author or maintainer, it can always be reopened if you see that carry on been useful.

            Anyway, thank you for your interest in contribute :heart:
          days-before-pr-stale: 60
          days-before-pr-close: 30
          stale-pr-label: 'stale'
          exempt-pr-labels: 'keep' # Don't mark PR's with this label as stale
          labels-to-remove-when-unstale: 'stale'
          exempt-draft-pr: true
          debug-only: ${{ github.event.inputs.debug-only == 'true' }}
          enable-statistics: true
